import { apiGet } from "../../lib/api";
import { StudioFrame } from "../../components/StudioChrome";
import { Metric, ResearchMetrics, ResearchPage, ResearchPanel, StatusPill } from "../../components/ResearchWorkspace";
export const dynamic="force-dynamic";
type Summary={observations:number;connectors:number;sources:{source:string;count:number}[];last_run:null|{connector_id:string;status:string;started_at:string;accepted_count:number}};
type Connector={id:string;version:string;description:string;schedule:string;state:null|{last_success_at:string|null;health?:string}};
type Observation={id:string;source:string;topic:string|null;metric:string;value:number|null;observed_at:string};
async function safeGet<T>(p:string,f:T){try{return await apiGet<T>(p)}catch{return f}}
export default async function SignalLake(){const [s,c,o]=await Promise.all([safeGet<Summary>("/api/v1/signal-lake/summary",{observations:0,connectors:0,sources:[],last_run:null}),safeGet<Connector[]>("/api/v1/connectors",[]),safeGet<Observation[]>("/api/v1/observations?limit=30",[])]);return <StudioFrame active="Evidence Lake"><ResearchPage eyebrow="Evidence Foundation" title="Evidence Lake" subtitle="Immutable observations with source identity, provenance and replayable ingestion history.">
 <ResearchMetrics><Metric label="Observations" value={s.observations.toLocaleString()}/><Metric label="Connectors" value={s.connectors}/><Metric label="Independent sources" value={s.sources.length} tone="violet"/><Metric label="Last ingestion" value={s.last_run?.status??"Not yet"} tone={s.last_run?.status==="succeeded"?"green":"amber"}/></ResearchMetrics>
 <div className="researchTwoCol wideLeft"><ResearchPanel title="Recent observations" subtitle="Latest immutable evidence entering YetSee."><div className="observationTableV2"><div className="tableHeader"><span>Observed</span><span>Source</span><span>Topic / metric</span><span>Value</span></div>{o.map(x=><div className="tableRow" key={x.id}><span>{new Date(x.observed_at).toLocaleString()}</span><div><StatusPill tone={x.source==="google_trends"?"green":"blue"}>{x.source}</StatusPill></div><div><strong>{x.topic??x.metric}</strong><small>{x.metric}</small></div><b>{x.value??"—"}</b></div>)}</div></ResearchPanel><ResearchPanel title="Source registry" subtitle="Connector-backed evidence families." className="stickyPanel"><div className="sourceRegistryV2">{c.map(x=><div key={x.id}><span className="sourceRegistryIcon">⌁</span><div><strong>{x.id}</strong><small>{x.description}</small></div><StatusPill tone={x.state?.health==="healthy"?"green":"slate"}>{x.state?.health??"ready"}</StatusPill></div>)}</div></ResearchPanel></div>
 </ResearchPage></StudioFrame>}
