"use client";

import { useEffect, useState } from "react";

type Source={evidence_link_id:string;stance:string;weight:number;passage_id:string;pmid?:string|null;doi?:string|null;title:string;source_url?:string|null;text:string};
type Profile={relationship_id:string;subject:string;predicate:string;object:string;supporting_count:number;contradicting_count:number;contextual_count:number;independent_publication_count:number;agreement:string;strength:string;sources:Source[]};
const humanize=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function ScientificEvidenceProfiles({investigationId}:{investigationId:string}){
 const [profiles,setProfiles]=useState<Profile[]>([]);const [open,setOpen]=useState<string|null>(null);
 useEffect(()=>{let active=true;async function load(){const r=await fetch(`/api/investigations/${investigationId}/evidence-profiles`,{cache:"no-store"});if(!r.ok||!active)return;const b=await r.json();setProfiles(Array.isArray(b)?b:[])}void load();return()=>{active=false}},[investigationId]);
 if(!profiles.length)return null;
 return <section className="scientificEvidenceProfiles"><header><div><span className="labLabel">Scientific evidence</span><h3>What does the literature support?</h3><p>Simple conclusions first. Open any relationship to inspect the studies and source passages behind it.</p></div><span className="evidenceBoundary">Claims ≠ Evidence</span></header><div className="evidenceProfileList">{profiles.map(p=>{const expanded=open===p.relationship_id;return <article className={`evidenceProfileCard ${p.strength}`} key={p.relationship_id}><div className="evidenceProfileMain"><div><strong>{p.subject}</strong><span>{humanize(p.predicate).toLowerCase()}</span><strong>{p.object}</strong></div><div className="evidenceProfileSignals"><b>{humanize(p.strength)} evidence</b><span>{humanize(p.agreement)}</span><small>{p.independent_publication_count} independent {p.independent_publication_count===1?"study":"studies"}</small></div><button onClick={()=>setOpen(expanded?null:p.relationship_id)}>{expanded?"Hide evidence":"View evidence"}</button></div>{expanded&&<div className="evidenceProfileDetail"><div className="evidenceCounts"><span><b>{p.supporting_count}</b> Supporting</span><span><b>{p.contradicting_count}</b> Contradicting</span><span><b>{p.contextual_count}</b> Contextual</span><span><b>{p.independent_publication_count}</b> Independent</span></div><div className="evidenceSources">{p.sources.map(s=><article key={s.evidence_link_id}><div><span className={`sourceStance ${s.stance}`}>{humanize(s.stance)}</span><strong>{s.title}</strong><small>{s.pmid?`PMID ${s.pmid}`:s.doi??"Scientific publication"}</small></div><p>{s.text}</p>{s.source_url&&<a href={s.source_url} target="_blank" rel="noreferrer">View source ↗</a>}</article>)}</div><small className="mechanicsNote">Assessment is derived from investigation-scoped canonical passages. Derived claims and scientific memory are not counted as evidence.</small></div>}</article>})}</div></section>;
}
